<a href="https://colab.research.google.com/github/derewor/SNP_for_GWAS/blob/main/gwas_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#df1 = pd.read_csv('/content/chr1_snp.csv')

In [ ]:
#df2 = pd.read_csv('/content/chr2_snps.csv')

In [ ]:
#df3 = pd.read_csv('/content/chr3_snps.csv')

In [ ]:
#df4 = pd.read_csv('/content/chr4_snps.csv')
#

In [ ]:
#df5 = pd.read_csv('/content/chr5_snps.csv')

In [ ]:
geno = pd.read_csv('/content/geno.csv')

In [ ]:
geno.head()

,rs,alleles,chrom,pos,strand,assembly#,center,protLSID,assayLSID,panelLSID,...,9903,9904,9906,9927,9938,9942,9948,9949,9950,10005
0,2,A/T,1,92,NaN,NaN,NaN,NaN,NaN,NaN,...,A,T,A,T,T,A,A,A,T,A
1,3,A/T,1,110,NaN,NaN,NaN,NaN,NaN,NaN,...,A,A,A,A,A,A,A,A,T,A
2,4,A/T,1,253,NaN,NaN,NaN,NaN,NaN,NaN,...,A,A,A,A,A,A,A,A,T,A
3,5,A/T,1,346,NaN,NaN,NaN,NaN,NaN,NaN,...,T,A,A,A,A,T,A,A,A,A
4,6,A/T,1,353,NaN,NaN,NaN,NaN,NaN,NaN,...,A,A,T,A,A,A,A,A,A,A

In [ ]:
df5.head()

,Unnamed: 0,53,62,198,251,257,269,304,341,408,...,26970761,26970843,26971522,26973058,26974485,26974816,26974820,26974938,26975272,26975377
0,430,0,0,1,0,1,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
1,991,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
2,1062,0,0,0,0,1,1,0,1,0,...,0,0,0,0,0,1,0,0,0,1
3,1063,0,0,0,0,1,1,0,1,0,...,0,0,0,0,0,1,0,0,0,1
4,1254,0,0,0,0,1,1,0,0,0,...,0,0,1,0,0,1,0,0,0,1

In [ ]:
df5.shape

(222, 110047)

In [ ]:
# merge the above df1, df2, df3, df4 anf d5 based on index 0
geno = pd.concat([df1, df2, df3, df4, df5], axis=1)

In [ ]:
geno.shape

(222, 512159)

In [ ]:
geno.tail()

,Unnamed: 0,92,110,253,346,353,363,419,502,508,...,26970761,26970843,26971522,26973058,26974485,26974816,26974820,26974938,26975272,26975377
217,9948,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,1
218,9949,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
219,9950,1,1,1,0,0,0,1,0,1,...,0,1,0,0,1,1,0,0,1,0
220,10005,0,0,0,0,0,0,0,0,0,...,0,1,0,1,0,1,0,0,1,0
221,10017,0,0,0,0,0,0,0,0,0,...,0,1,0,0,1,1,0,0,1,0

In [ ]:
# geno = pd.read_csv('geno.csv')

In [ ]:
geno.columns = geno.iloc[0]
geno = geno[2:]

In [ ]:
geno1 = geno.rename(columns={'Accession':'position'})
geno1['position'] = geno1['position'].astype(int)

In [ ]:
meta_data = pd.read_csv('metadata.csv')
meta_data = meta_data.set_index('Unnamed: 0')
meta_data['position'] = meta_data['position'].astype(int)

In [ ]:
# for tassel the matrix needs to be converted to nucleotide. the nucleotide is added for analysis purpose)
geno_hmp = geno1.replace({0: 'A', 1: 'T'})
geno_hmp = geno_hmp

In [ ]:
geno_hmp.insert(0, 'rs', geno.index.astype(str))

In [ ]:
geno_hmp.insert(1, 'alleles', 'A/T')

In [ ]:
geno_hmp.insert(3, 'strand', '+')

In [ ]:
geno_hmp.insert(4, 'assembly#', 'NA')
geno_hmp.insert(5, 'center', 'NA')
geno_hmp.insert(6, 'protLSID', 'NA')
geno_hmp.insert(7, 'assayLSID', 'NA')
geno_hmp.insert(8, 'panelLSID', 'NA')
geno_hmp.insert(9, 'QCcode', 'NA')

In [ ]:
geno_hmp

,rs,alleles,position,strand,assembly#,center,protLSID,assayLSID,panelLSID,QCcode,...,9903,9904,9906,9927,9938,9942,9948,9949,9950,10005
2,2,A/T,92,+,NA,NA,NA,NA,NA,NA,...,A,T,A,T,T,A,A,A,T,A
3,3,A/T,110,+,NA,NA,NA,NA,NA,NA,...,A,A,A,A,A,A,A,A,T,A
4,4,A/T,253,+,NA,NA,NA,NA,NA,NA,...,A,A,A,A,A,A,A,A,T,A
5,5,A/T,346,+,NA,NA,NA,NA,NA,NA,...,T,A,A,A,A,T,A,A,A,A
6,6,A/T,353,+,NA,NA,NA,NA,NA,NA,...,A,A,T,A,A,A,A,A,A,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512151,512151,A/T,26974816,+,NA,NA,NA,NA,NA,NA,...,T,T,T,T,T,A,T,T,T,T
512152,512152,A/T,26974820,+,NA,NA,NA,NA,NA,NA,...,T,A,A,A,T,A,A,A,A,A
512153,512153,A/T,26974938,+,NA,NA,NA,NA,NA,NA,...,A,T,A,A,A,A,T,A,A,A
512154,512154,A/T,26975272,+,NA,NA,NA,NA,NA,NA,...,T,A,T,T,T,A,A,T,T,T
512155,512155,A/T,26975377,+,NA,NA,NA,NA,NA,NA,...,A,T,A,A,A,A,T,A,A,A

In [ ]:
#order_column = ['rs#', 'alleles', 'chromosome', 'position']
#meta_data = meta_data[order_column]
meta_data.head(20)

            position chromosome
Unnamed: 0
0                 92       chr1
1                110       chr1
2                253       chr1
3                346       chr1
4                353       chr1
5                363       chr1
6                419       chr1
7                502       chr1
8                508       chr1
9                698       chr1
10               956       chr1
11              1645       chr1
12              1974       chr1
13              3084       chr1
14              7202       chr1
15              7464       chr1
16              7572       chr1
17             10294       chr1
18             10904       chr1
19             11293       chr1

In [ ]:
# merge the metadta and gene_hmp files.
genotype_hmp = pd.merge(meta_data, geno_hmp, how='inner', left_on='position', right_on='position')
genotype_hmp = genotype_hmp.drop_duplicates(subset=['position', 'chromosome'], keep='first')
genotype_hmp.head()

,position,chromosome,rs,alleles,strand,assembly#,center,protLSID,assayLSID,panelLSID,...,9903,9904,9906,9927,9938,9942,9948,9949,9950,10005
0,92,chr1,2,A/T,+,NA,NA,NA,NA,NA,...,A,T,A,T,T,A,A,A,T,A
1,110,chr1,3,A/T,+,NA,NA,NA,NA,NA,...,A,A,A,A,A,A,A,A,T,A
2,253,chr1,4,A/T,+,NA,NA,NA,NA,NA,...,A,A,A,A,A,A,A,A,T,A
3,346,chr1,5,A/T,+,NA,NA,NA,NA,NA,...,T,A,A,A,A,T,A,A,A,A
4,353,chr1,6,A/T,+,NA,NA,NA,NA,NA,...,A,A,T,A,A,A,A,A,A,A

In [ ]:
cols = genotype_hmp.columns.tolist()
# Remove the columns first
cols.remove('position')
cols.remove('chromosome')
# Insert them at desired locations
cols.insert(2, 'position')      # column index 2 = 3rd column
cols.insert(3, 'chromosome')    # column index 3 = 4th column
# Reorder dataframe
genotype_hmp = genotype_hmp[cols]

In [ ]:
genotype_hmp.head()

,rs,alleles,position,chromosome,strand,assembly#,center,protLSID,assayLSID,panelLSID,...,9903,9904,9906,9927,9938,9942,9948,9949,9950,10005
0,2,A/T,92,chr1,+,NA,NA,NA,NA,NA,...,A,T,A,T,T,A,A,A,T,A
1,3,A/T,110,chr1,+,NA,NA,NA,NA,NA,...,A,A,A,A,A,A,A,A,T,A
2,4,A/T,253,chr1,+,NA,NA,NA,NA,NA,...,A,A,A,A,A,A,A,A,T,A
3,5,A/T,346,chr1,+,NA,NA,NA,NA,NA,...,T,A,A,A,A,T,A,A,A,A
4,6,A/T,353,chr1,+,NA,NA,NA,NA,NA,...,A,A,T,A,A,A,A,A,A,A

In [ ]:
genotype_hmp.to_csv(
    'geno.hmp1.txt',
    sep='\t',
    index=False
)

print("HapMap file saved!")

HapMap file saved!

In [ ]:
#  merge the meta data and geno datafiles.
genotype_hmp.rs.nunique()

508295

In [ ]:
genotype_hmp[['position','chromosome']].duplicated().sum()

0

In [ ]:
geno.head()

,Accession,991,1062,1254,1925,2276,5856,6009,6011,6012,...,9903,9904,9906,9927,9938,9942,9948,9949,9950,10005
2,92,0,1,0,1,0,0,0,0,0,...,0,1,0,1,1,0,0,0,1,0
3,110,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,253,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
5,346,1,0,1,0,1,1,1,1,1,...,1,0,0,0,0,1,0,0,0,0
6,353,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [ ]:
geno_t = geno.T
geno_t.columns = geno_t.iloc[0]
geno_t = geno_t[1:]
geno_t0 = geno_t.reset_index()
geno_t1 = geno_t0.rename(columns={0:'position'})
geno_t1.head()

Accession,position,92,110,253,346,353,363,419,502,508,...,26970761,26970843,26971522,26973058,26974485,26974816,26974820,26974938,26975272,26975377
0,991,0,0,0,1,0,0,0,1,1,...,0,1,0,0,0,1,0,0,1,0
1,1062,1,0,0,0,1,0,0,0,1,...,0,0,0,0,0,1,0,0,0,1
2,1254,0,0,0,1,0,0,0,1,1,...,0,0,1,0,0,1,0,0,0,1
3,1925,1,0,0,0,0,0,0,0,1,...,1,0,0,1,0,1,0,0,1,0
4,2276,0,0,0,1,0,0,0,1,1,...,1,0,0,0,0,1,1,0,1,0

In [ ]:
# your genotype dataframe
# geno shape: (SNPs x individuals)
geno_str = geno.copy()

# # reproducible random sampling
geno_thin = geno_str.sample(n=10000, random_state=42)

# print(geno_thin.shape)
geno_thin.head()

,Accession,991,1062,1254,1925,2276,5856,6009,6011,6012,...,9903,9904,9906,9927,9938,9942,9948,9949,9950,10005
22418,8102465,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
281116,15789747,1,1,0,0,0,0,1,1,1,...,1,0,0,0,0,1,0,1,0,1
397667,17105271,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
291595,16824406,0,1,1,0,1,1,1,1,1,...,1,0,1,0,1,1,0,0,0,0
446078,12525918,1,0,0,0,0,1,0,0,0,...,1,1,1,0,0,1,1,1,0,0

In [ ]:
# transpose the geno_thin data.
geno_thinT = geno_thin.T
geno_thinT.columns = geno_thinT.iloc[0]
geno_thinT = geno_thinT[1:]
geno_thinT.head()

Accession,8102465,15789747,17105271,16824406,12525918,17878876,22830042,8427108,991053,2039661,...,21173947,12217364,309023,16756089,16639799,13273689,10310264,15219782,12807053,8507149
0,,,,,,,,,,,,,,,,,,,,,
991,0,1,0,0,1,0,0,1,0,0,...,0,0,0,1,0,1,1,1,1,0
1062,0,1,0,1,0,0,0,1,0,0,...,0,0,0,1,0,1,0,1,1,0
1254,0,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,1,1,1,1,0
1925,0,0,0,0,0,0,0,1,0,0,...,0,1,0,1,0,1,0,1,1,0
2276,1,0,1,1,0,0,0,1,1,0,...,0,1,0,0,0,1,0,1,1,0

In [ ]:
geno_diploid = geno_thinT.loc[geno_thinT.index.repeat(2)].copy()

In [ ]:
geno_diploid = geno_diploid.reset_index()#.drop(columns=['level_0', 'index'])
geno_diploid.head()

Accession,0,8102465,15789747,17105271,16824406,12525918,17878876,22830042,8427108,991053,...,21173947,12217364,309023,16756089,16639799,13273689,10310264,15219782,12807053,8507149
0,991,0,1,0,0,1,0,0,1,0,...,0,0,0,1,0,1,1,1,1,0
1,991,0,1,0,0,1,0,0,1,0,...,0,0,0,1,0,1,1,1,1,0
2,1062,0,1,0,1,0,0,0,1,0,...,0,0,0,1,0,1,0,1,1,0
3,1062,0,1,0,1,0,0,0,1,0,...,0,0,0,1,0,1,0,1,1,0
4,1254,0,0,0,1,0,0,0,1,0,...,0,0,0,0,0,1,1,1,1,0

In [ ]:
# organize the data for STRUCTURE analysis
# structure_geno = geno_thinT.applymap(lambda x: [1, 1] if x ==0 else[2,2])

/var/folders/rk/kh1g1yz15_b539v1q19bprcr0000gn/T/ipykernel_14904/3448655741.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  structure_geno = geno_thinT.applymap(lambda x: [1, 1] if x ==0 else[2,2])

In [ ]:
# structure_geno.head()

Accession,8102465,15789747,17105271,16824406,12525918,17878876,22830042,8427108,991053,2039661,...,26080323,1550517,28129182,2385983,3466245,11965943,18540426,3915936,25125552,8716038
0,,,,,,,,,,,,,,,,,,,,,
991,"[1, 1]","[2, 2]","[1, 1]","[1, 1]","[2, 2]","[1, 1]","[1, 1]","[2, 2]","[1, 1]","[1, 1]",...,"[1, 1]","[1, 1]","[2, 2]","[2, 2]","[2, 2]","[2, 2]","[1, 1]","[2, 2]","[1, 1]","[1, 1]"
1062,"[1, 1]","[2, 2]","[1, 1]","[2, 2]","[1, 1]","[1, 1]","[1, 1]","[2, 2]","[1, 1]","[1, 1]",...,"[1, 1]","[1, 1]","[1, 1]","[1, 1]","[2, 2]","[1, 1]","[1, 1]","[2, 2]","[1, 1]","[1, 1]"
1254,"[1, 1]","[1, 1]","[1, 1]","[2, 2]","[1, 1]","[1, 1]","[1, 1]","[2, 2]","[1, 1]","[1, 1]",...,"[1, 1]","[1, 1]","[1, 1]","[1, 1]","[2, 2]","[2, 2]","[1, 1]","[2, 2]","[1, 1]","[1, 1]"
1925,"[1, 1]","[1, 1]","[1, 1]","[1, 1]","[1, 1]","[1, 1]","[1, 1]","[2, 2]","[1, 1]","[1, 1]",...,"[1, 1]","[2, 2]","[1, 1]","[2, 2]","[2, 2]","[1, 1]","[1, 1]","[2, 2]","[1, 1]","[1, 1]"
2276,"[2, 2]","[1, 1]","[2, 2]","[2, 2]","[1, 1]","[1, 1]","[1, 1]","[2, 2]","[2, 2]","[1, 1]",...,"[1, 1]","[1, 1]","[1, 1]","[2, 2]","[2, 2]","[1, 1]","[1, 1]","[1, 1]","[1, 1]","[1, 1]"

In [ ]:
# expand each SNP into two columns.
geno_df = pd.DataFrame(geno_diploid.apply(lambda row: sum(row, []), axis=1). tolist(), index=geno_diploid.index)
geno_df.head()

TypeError: can only concatenate list (not "int") to list

In [ ]:
# save to file.
geno_diploid.insert(0, "ID", geno_deploid.index)

NameError: name 'geno_deploid' is not defined

In [ ]:
geno_df.head()

,ID,0,1,2,3,4,5,6,7,8,...,9990,9991,9992,9993,9994,9995,9996,9997,9998,9999
0,,,,,,,,,,,,,,,,,,,,,
991,991,1,1,2,2,1,1,1,1,2,...,2,2,1,1,2,2,1,1,1,1
1062,1062,1,1,2,2,1,1,2,2,1,...,1,1,1,1,2,2,1,1,1,1
1254,1254,1,1,1,1,1,1,2,2,1,...,2,2,1,1,2,2,1,1,1,1
1925,1925,1,1,1,1,1,1,1,1,1,...,1,1,1,1,2,2,1,1,1,1
2276,2276,2,2,1,1,2,2,2,2,1,...,1,1,1,1,1,1,1,1,1,1

In [ ]:
geno_diploid.to_csv("output_structure", sep="\t", header=False, index=False)

In [ ]:
dfx = pd.read_csv('output_structure', delimiter='\t')
dfx.head()

,991,0,1,0.1,0.2,1.1,0.3,0.4,1.2,0.5,...,0.6859,0.6860,0.6861,1.3131,0.6862,1.3132,1.3133,1.3134,1.3135,0.6863
0,991,0,1,0,0,1,0,0,1,0,...,0,0,0,1,0,1,1,1,1,0
1,1062,0,1,0,1,0,0,0,1,0,...,0,0,0,1,0,1,0,1,1,0
2,1062,0,1,0,1,0,0,0,1,0,...,0,0,0,1,0,1,0,1,1,0
3,1254,0,0,0,1,0,0,0,1,0,...,0,0,0,0,0,1,1,1,1,0
4,1254,0,0,0,1,0,0,0,1,0,...,0,0,0,0,0,1,1,1,1,0

In [ ]:
geno_hmp = pd.read_csv('geno.hmp2.txt', sep='\t')

In [ ]:
geno_hmp.head()

,rs,alleles,position,chromosome,strand,assembly#,center,protLSID,assayLSID,panelLSID,...,9903,9904,9906,9927,9938,9942,9948,9949,9950,10005
0,2,A/T,92,chr1,+,NaN,NaN,NaN,NaN,NaN,...,A,T,A,T,T,A,A,A,T,A
1,3,A/T,110,chr1,+,NaN,NaN,NaN,NaN,NaN,...,A,A,A,A,A,A,A,A,T,A
2,4,A/T,253,chr1,+,NaN,NaN,NaN,NaN,NaN,...,A,A,A,A,A,A,A,A,T,A
3,5,A/T,346,chr1,+,NaN,NaN,NaN,NaN,NaN,...,T,A,A,A,A,T,A,A,A,A
4,6,A/T,353,chr1,+,NaN,NaN,NaN,NaN,NaN,...,A,A,T,A,A,A,A,A,A,A

In [ ]:
geno_hmp['chromosome'] = geno_hmp['chromosome'].str.replace('chr','').astype(int)

In [ ]:
# fill NA with 'NA'
geno_hmp = geno_hmp.fillna('NA')

In [ ]:
geno_hmp['strand'] = geno_hmp['strand'].str.replace('+', 'NA')

In [ ]:
cols = list(geno_hmp.columns)

# remove columns
cols.remove('chromosome')
cols.remove('position')

# insert back in correct order
cols.insert(2, 'chromosome')
cols.insert(3, 'position')

geno_hmp = geno_hmp[cols]

In [ ]:
geno_hmp = geno_hmp.rename(columns={'chromosome':'chrom',
                                                'position':'pos'})

In [ ]:
geno_hmp.head()

,rs,alleles,chrom,pos,strand,assembly#,center,protLSID,assayLSID,panelLSID,...,9903,9904,9906,9927,9938,9942,9948,9949,9950,10005
0,2,A/T,1,92,NA,NA,NA,NA,NA,NA,...,A,T,A,T,T,A,A,A,T,A
1,3,A/T,1,110,NA,NA,NA,NA,NA,NA,...,A,A,A,A,A,A,A,A,T,A
2,4,A/T,1,253,NA,NA,NA,NA,NA,NA,...,A,A,A,A,A,A,A,A,T,A
3,5,A/T,1,346,NA,NA,NA,NA,NA,NA,...,T,A,A,A,A,T,A,A,A,A
4,6,A/T,1,353,NA,NA,NA,NA,NA,NA,...,A,A,T,A,A,A,A,A,A,A

In [ ]:
geno_hmp.chrom.unique()

array([1, 2, 3, 4, 5])

In [ ]:
geno_hmp.to_csv('geno.hmp.txt', sep='\t', index=False, header=True)