<a href="https://colab.research.google.com/github/derewor/SNP_for_GWAS/blob/main/SNP_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/output_structure-3', sep='\t')

In [ ]:
df.head()

,991,0,1,0.1,0.2,1.1,0.3,0.4,1.2,0.5,...,0.6859,0.6860,0.6861,1.3131,0.6862,1.3132,1.3133,1.3134,1.3135,0.6863
0,991,0,1,0,0,1,0,0,1,0,...,0,0,0,1,0,1,1,1,1,0
1,1062,0,1,0,1,0,0,0,1,0,...,0,0,0,1,0,1,0,1,1,0
2,1062,0,1,0,1,0,0,0,1,0,...,0,0,0,1,0,1,0,1,1,0
3,1254,0,0,0,1,0,0,0,1,0,...,0,0,0,0,0,1,1,1,1,0
4,1254,0,0,0,1,0,0,0,1,0,...,0,0,0,0,0,1,1,1,1,0

In [ ]:
accession = df.iloc[:,0].unique()

In [ ]:
ids = pd.DataFrame(accession)
ids.head()

      0
0   991
1  1062
2  1254
3  1925
4  2276

In [ ]:
import pandas as pd

# Load Q matrix (no headers)
q = pd.read_csv("/content/Q matrix.txt", sep=r"\s+", header=None)

# Load IDs (same order as input)
#ids = pd.read_csv("ids.txt", header=None)

# Combine
q.insert(0, "Taxa", ids)

# Add column names
q.columns = ["Taxa"] + [f"Q{i+1}" for i in range(q.shape[1]-1)]

# Save
q.to_csv("Q_matrix_for_TASSEL.txt", sep="\t", index=False)

In [ ]:
df2 = pd.read_csv('/content/Q_matrix_for_TASSEL.txt', sep='\t')

In [ ]:
df2.head()

   Taxa  Q1  Q2   Q3  Q4 Q5      Q6      Q7      Q8
0   991   1   1  (0)   1  :  0.1314  0.0090  0.8596
1  1062   2   2  (0)   1  :  0.0844  0.0010  0.9146
2  1254   3   3  (0)   1  :  0.4968  0.1034  0.3998
3  1925   4   4  (0)   1  :  0.0770  0.0762  0.8468
4  2276   5   5  (0)   1  :  0.0046  0.1314  0.8640

In [ ]:
selected_columns = ['Taxa','Q6', 'Q7','Q8']

In [ ]:
Q_matrix_tassel =df2[selected_columns]

In [ ]:
Q_matrix_tassel.head()

   Taxa      Q6      Q7      Q8
0   991  0.1314  0.0090  0.8596
1  1062  0.0844  0.0010  0.9146
2  1254  0.4968  0.1034  0.3998
3  1925  0.0770  0.0762  0.8468
4  2276  0.0046  0.1314  0.8640

In [ ]:
Q_matrix_tassel.to_csv("Q_matrix_for_TASSEL.txt", sep="\t", index=False)

In [ ]:
germ = pd.read_csv('/content/pheno_germ.csv', sep=';')
germ.drop(germ.columns[0], axis=1, inplace=True)

In [ ]:
germ.head()

   Accession  germ_inhib
0        991        0.00
1       1062        0.14
2       1254       -0.16
3       1925        0.33
4       2276        0.00

In [ ]:
germ.columns

Index(['Unnamed: 0', 'Accession', 'germ_inhib'], dtype='object')

In [ ]:
germ.to_csv("phen_germ.txt", sep="\t", index=False)

In [ ]:
dfr = pd.read_csv('/content/pheno_root.csv', sep=';')

In [ ]:
# drop the index before saving.

dfr.drop(dfr.columns[0], axis=1, inplace=True)

In [ ]:
dfr.head()

   Accession  root_inhib
0        991        0.17
1       1062       -0.28
2       1254       -0.59
3       1925        0.04
4       2276       -0.51

In [ ]:
dfr.to_csv("phen_root.txt", sep="\t", index=False)

In [ ]:
dfq = pd.read_csv('/content/Q_matrix.txt', sep='\t')

In [ ]:
dfq.head(10)

   Taxa     Q1     Q2     Q3
0   991  0.131  0.009  0.860
1  1062  0.084  0.001  0.915
2  1254  0.497  0.103  0.400
3  1925  0.077  0.076  0.847
4  2276  0.005  0.131  0.864
5  5856  0.999  0.001  0.000
6  6009  1.000  0.000  0.000
7  6011  1.000  0.000  0.000
8  6012  1.000  0.000  0.000
9  6013  1.000  0.000  0.000

In [ ]:
# strip any empty spaces from taxa columns.
dfq['Taxa'] = dfq['Taxa'].astype(str).str.strip()

In [ ]:
dfq.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Taxa    173 non-null    object
 1   Q1      173 non-null    float64
 2   Q2      173 non-null    float64
 3   Q3      173 non-null    float64
dtypes: float64(3), object(1)
memory usage: 5.5+ KB

In [ ]:
# save dfq as .hmp.txt file

dfq.to_csv("Q_matrix.hmp.txt", sep="\t", index=False)

In [ ]:
dfq1 = pd.read_csv('/content/Q_matrix.hmp.txt', sep='\t')

In [ ]:
dfq1.head()

   Taxa     Q1     Q2     Q3
0   991  0.131  0.009  0.860
1  1062  0.084  0.001  0.915
2  1254  0.497  0.103  0.400
3  1925  0.077  0.076  0.847
4  2276  0.005  0.131  0.864

In [ ]:
from statsmodels.stats.multitest import multipletests

In [ ]:
gwas = pd.read_csv('/content/MLM_roots_result.csv.txt', sep=',')

In [ ]:
gwas.head()

,Trait,Marker,Chr,Pos,df,F,p,add_effect,add_F,add_p,dom_effect,dom_F,dom_p,errordf,MarkerR2,Genetic Var,Residual Var,-2LnLikelihood
0,RL,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,173,NaN,0.03039,0.05544,110.03958
1,RL,1446.0,1.0,523651.0,1,16.98241,0.000059,NaN,NaN,NaN,NaN,NaN,NaN,173,0.09873,0.03039,0.05544,110.03958
2,RL,1480.0,1.0,533159.0,1,12.73008,0.000467,NaN,NaN,NaN,NaN,NaN,NaN,173,0.07401,0.03039,0.05544,110.03958
3,RL,3566.0,1.0,1500969.0,1,15.22626,0.000137,NaN,NaN,NaN,NaN,NaN,NaN,173,0.08852,0.03039,0.05544,110.03958
4,RL,4156.0,1.0,1671817.0,1,12.99599,0.000409,NaN,NaN,NaN,NaN,NaN,NaN,173,0.07556,0.03039,0.05544,110.03958

In [ ]:
gwas = gwas[1:]

In [ ]:
gwas['FDR_p'] = multipletests(
    gwas['p'],
    method='fdr_bh'
)[1]

In [ ]:
import numpy as  np
gwas['log10_p'] = -np.log10(gwas['p'])

In [ ]:
gwas.head()

,Trait,Marker,Chr,Pos,df,F,p,add_effect,add_F,add_p,dom_effect,dom_F,dom_p,errordf,MarkerR2,Genetic Var,Residual Var,-2LnLikelihood,FDR_p,log10_p
1,RL,1446.0,1.0,523651.0,1,16.98241,0.000059,NaN,NaN,NaN,NaN,NaN,NaN,173,0.09873,0.03039,0.05544,110.03958,0.000436,4.231377
2,RL,1480.0,1.0,533159.0,1,12.73008,0.000467,NaN,NaN,NaN,NaN,NaN,NaN,173,0.07401,0.03039,0.05544,110.03958,0.000775,3.330646
3,RL,3566.0,1.0,1500969.0,1,15.22626,0.000137,NaN,NaN,NaN,NaN,NaN,NaN,173,0.08852,0.03039,0.05544,110.03958,0.000516,3.863470
4,RL,4156.0,1.0,1671817.0,1,12.99599,0.000409,NaN,NaN,NaN,NaN,NaN,NaN,173,0.07556,0.03039,0.05544,110.03958,0.000746,3.388011
5,RL,4230.0,1.0,1696214.0,1,12.58133,0.000503,NaN,NaN,NaN,NaN,NaN,NaN,173,0.07315,0.03039,0.05544,110.03958,0.000790,3.298492

In [ ]:
sig_snps = gwas[gwas['log10_p'] >= 5]

In [ ]:
sig_snps.shape

(25, 20)

In [ ]:
pheno = pd.read_csv('/content/pheno.csv')
pheno

     Unnamed: 0  Accession  root_inhib  inhib_ratio  gr_ratio
0             0        991        0.20         0.80     0.475
1             1       1062       -0.22         1.22     0.689
2             2       1063        0.13         0.87     0.211
3             3       1254       -0.39         1.39     0.635
4             4       1925        0.14         0.86     0.378
..          ...        ...         ...          ...       ...
197         197       9942        0.09         0.91     0.440
198         198       9948        0.00         1.00     0.541
199         199       9949       -0.01         1.01     0.385
200         200       9950        0.30         0.70     0.379
201         201      10005        0.32         0.68     0.322

[202 rows x 5 columns]

In [ ]:
pheno.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   202 non-null    int64
 1   Accession    202 non-null    int64
 2   root_inhib   202 non-null    float64
 3   inhib_ratio  202 non-null    float64
 4   gr_ratio     202 non-null    float64
dtypes: float64(3), int64(2)
memory usage: 8.0 KB

In [ ]:
# drop the first column
pheno.drop(pheno.columns[0], axis=1, inplace=True)

In [ ]:
pheno['gr_ratio'] = pheno.gr_ratio.round(2)

In [ ]:
pheno

     Accession  root_inhib  inhib_ratio  gr_ratio
0          991        0.20         0.80     0.475
1         1062       -0.22         1.22     0.689
2         1063        0.13         0.87     0.211
3         1254       -0.39         1.39     0.635
4         1925        0.14         0.86     0.378
..         ...         ...          ...       ...
197       9942        0.09         0.91     0.440
198       9948        0.00         1.00     0.541
199       9949       -0.01         1.01     0.385
200       9950        0.30         0.70     0.379
201      10005        0.32         0.68     0.322

[202 rows x 4 columns]

In [ ]:
# chance the data type of accession to string.
pheno['Accession'] = pheno['Accession'].astype(str)

In [ ]:
pheno.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Accession    202 non-null    object
 1   root_inhib   202 non-null    float64
 2   inhib_ratio  202 non-null    float64
 3   gr_ratio     202 non-null    float64
dtypes: float64(3), object(1)
memory usage: 6.4+ KB

In [ ]:
# save as hmp.txt without index.
pheno.to_csv("pheno.hmp.txt", sep="\t", index=False)

In [ ]:
geno = pd.read_csv('/content/geno.hmp-3.txt', sep='\t')

In [ ]:
geno.head()

,rs#,alleles,pos,chrom,strand,assembly#,center,protLSID,assayLSID,panelLSID,...,9903,9904,9906,9927,9938,9942,9948,9949,9950,10005
0,0,A/T,92,1,NaN,NaN,NaN,NaN,NaN,NaN,...,A,T,A,T,T,A,A,A,T,A
1,1,A/T,110,1,NaN,NaN,NaN,NaN,NaN,NaN,...,A,A,A,A,A,A,A,A,T,A
2,2,A/T,253,1,NaN,NaN,NaN,NaN,NaN,NaN,...,A,A,A,A,A,A,A,A,T,A
3,3,A/T,346,1,NaN,NaN,NaN,NaN,NaN,NaN,...,T,A,A,A,A,T,A,A,A,A
4,4,A/T,353,1,NaN,NaN,NaN,NaN,NaN,NaN,...,A,A,T,A,A,A,A,A,A,A

In [ ]:
# exchange the position of pos and chrom in the geno df.
cols = list(geno.columns)
a, b = cols.index('pos'), cols.index('chrom')
cols[b], cols[a] = cols[a], cols[b]
geno = geno[cols]

In [ ]:
geno.head()

,rs#,alleles,chrom,pos,strand,assembly#,center,protLSID,assayLSID,panelLSID,...,9903,9904,9906,9927,9938,9942,9948,9949,9950,10005
0,0,A/T,1,92,NaN,NaN,NaN,NaN,NaN,NaN,...,A,T,A,T,T,A,A,A,T,A
1,1,A/T,1,110,NaN,NaN,NaN,NaN,NaN,NaN,...,A,A,A,A,A,A,A,A,T,A
2,2,A/T,1,253,NaN,NaN,NaN,NaN,NaN,NaN,...,A,A,A,A,A,A,A,A,T,A
3,3,A/T,1,346,NaN,NaN,NaN,NaN,NaN,NaN,...,T,A,A,A,A,T,A,A,A,A
4,4,A/T,1,353,NaN,NaN,NaN,NaN,NaN,NaN,...,A,A,T,A,A,A,A,A,A,A

In [ ]:
# save geno as hmp.txt file without index.
geno.to_csv("geno.hmp.txt", sep="\t", index=False)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# import the the SNPs and select SNPs with -log10 values greated than 4.5.
mlm_df = pd.read_csv('/content/MLM_root_all.csv.txt', sep = ',')
#mlm_df = mlm_df.drop(columns = ['add_effect','add_F','add_p','dom_effect',	'dom_F',	'dom_p'])
mlm_df.shape

(1536465, 18)

In [ ]:
import numpy as np

In [ ]:
# calculate the inverse log 10 values.
mlm_df['log10_p'] = -np.log10(mlm_df['p']).round(2)
mlm_df.head()

,Trait,Marker,Chr,Pos,df,F,p,errordf,MarkerR2,Genetic Var,Residual Var,-2LnLikelihood,log10_p
0,RI,NaN,NaN,NaN,0,NaN,NaN,199,NaN,0.03006,0.05716,123.33577,NaN
1,RI,0.0,1.0,92.0,1,0.03414,0.85360,202,0.000168,0.03006,0.05716,123.33577,0.07
2,RI,1.0,1.0,110.0,1,1.04145,0.30874,202,0.005130,0.03006,0.05716,123.33577,0.51
3,RI,2.0,1.0,253.0,1,1.24757,0.26538,202,0.006150,0.03006,0.05716,123.33577,0.58
4,RI,3.0,1.0,346.0,1,2.56618,0.11077,202,0.012640,0.03006,0.05716,123.33577,0.96

In [ ]:
# filters snp rows where the -log10 values are greater than 4.5.
snps = mlm_df.query('log10_p > 4.0')
snps.shape

(381, 13)

In [ ]:
snps[['Chr','Pos']] = snps[['Chr','Pos']].astype(int)

/tmp/ipykernel_8802/1007601818.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  snps[['Chr','Pos']] = snps[['Chr','Pos']].astype(int)

In [ ]:
snps.head()

,Trait,Marker,Chr,Pos,df,F,p,errordf,MarkerR2,Genetic Var,Residual Var,-2LnLikelihood,log10_p
1374,RI,1373.0,1,505948,1,19.77551,0.000015,202,0.09742,0.03006,0.05716,123.33577,4.84
1445,RI,1444.0,1,523651,1,20.70879,0.000009,202,0.10201,0.03006,0.05716,123.33577,5.03
30676,RI,30675.0,1,10421043,1,20.11410,0.000012,202,0.09908,0.03006,0.05716,123.33577,4.91
30680,RI,30679.0,1,10421227,1,17.02184,0.000054,202,0.08385,0.03006,0.05716,123.33577,4.26
49286,RI,49285.0,1,13460657,1,20.60329,0.000010,202,0.10149,0.03006,0.05716,123.33577,5.01

In [ ]:
ri_df = snps.query('Trait =="RI"')
#gr_df = snps.query('Trait =="GR"')
print(ri_df.shape)
#print(gr_df.shape)

(75, 13)

In [ ]:
snps.Trait.unique()

array(['RI', 'IR', 'GR'], dtype=object)

In [ ]:
# extract the Chr and pos columns from the dataset.
snps_ri = ri_df[['Chr','Pos']]
#snps_gr = gr_df[['Chr','Pos']]
print(snps_ri.head())
#print(snps_gr.head())

       Chr       Pos
1374     1    505948
1445     1    523651
30676    1  10421043
30680    1  10421227
49286    1  13460657

In [ ]:
snps_ri = snps_ri.rename(columns=({'Chr':'Chromosome','Pos':'Start1'}))
#snps_gr = snps_gr.rename(columns=({'Chr':'Chromosome','Pos':'Start1'}))

In [ ]:
snps_ri.head()

       Chromosome    Start1
1374            1    505948
1445            1    523651
30676           1  10421043
30680           1  10421227
49286           1  13460657

In [ ]:
# snps_chr_pos['End1'] = snps_chr_pos['Start1'] + 1
# snp_data = snps_chr_pos.copy()

In [ ]:
!pip install pandas pyranges gffutils

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: pyranges in /usr/local/lib/python3.12/dist-packages (0.1.4)
Requirement already satisfied: gffutils in /usr/local/lib/python3.12/dist-packages (0.14)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: ncls>=0.0.63 in /usr/local/lib/python3.12/dist-packages (from pyranges) (0.0.70)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (from pyranges) (0.9.0)
Requirement already satisfied: sorted_nearest>=0.0.33 in /usr/local/lib/python3.12/dist-packages (from pyranges) (0.0.41)
Requirement already satisfied: natsort in /usr/local/lib/python3.12/dist-packages (from pyranges) (8.4.0)
Requirement already satisfied: pyfaidx>=0.5.5.2 in /usr/local/lib/python3.12/dist-packages (from gffutils) (0.9.0.4)
Requirement already satisfied: argh>=0.26.2 in /usr/local/lib/python3.12/dist-packages (from gffutils) (0.31.3)
Requirement already satisfied: argcomplete>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from gffutils) (3.6.3)
Requirement already satisfied: simplejson in /usr/local/lib/python3.12/dist-packages (from gffutils) (4.1.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from pyfaidx>=0.5.5.2->gffutils) (26.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
!wget https://zenodo.org/records/17371665/files/Araport11_GFF3_genes_transposons.20241001.gff.gz

--2026-05-19 13:57:39--  https://zenodo.org/records/17371665/files/Araport11_GFF3_genes_transposons.20241001.gff.gz
Resolving zenodo.org (zenodo.org)... 137.138.52.235, 137.138.153.219, 188.184.103.118, ...
Connecting to zenodo.org (zenodo.org)|137.138.52.235|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16479936 (16M) [application/octet-stream]
Saving to: ‘Araport11_GFF3_genes_transposons.20241001.gff.gz.2’

Araport11_GFF3_gene 100%[===================>]  15.72M   426KB/s    in 43s

2026-05-19 13:58:22 (376 KB/s) - ‘Araport11_GFF3_genes_transposons.20241001.gff.gz.2’ saved [16479936/16479936]

In [ ]:
!gunzip Araport11_GFF3_genes_transposons.20241001.gff.gz

gzip: Araport11_GFF3_genes_transposons.20241001.gff already exists; do you wish to overwrite (y or n)? n
	not overwritten

In [ ]:
gff_cols = [
    "Chromosome", "Source", "Feature",
    "Start", "End", "Score",
    "Strand", "Frame", "Attributes"
]

In [ ]:
gff = pd.read_csv(
    "Araport11_GFF3_genes_transposons.20241001.gff",
    sep="\t",
    comment="#",
    names=gff_cols,
    encoding="utf-8", encoding_errors="ignore"
)

In [ ]:
gff.head()

,Chromosome,Source,Feature,Start,End,Score,Strand,Frame,Attributes
0,Chr1,Araport11,gene,3631,5899,.,+,.,ID=AT1G01010;Name=AT1G01010;full_name=NAC doma...
1,Chr1,Araport11,mRNA,3631,5899,.,+,.,ID=AT1G01010.1;Name=AT1G01010.1;Parent=AT1G010...
2,Chr1,Araport11,CDS,3760,3913,.,+,0,ID=AT1G01010:CDS:1;Name=NAC001:CDS:1;Parent=AT...
3,Chr1,Araport11,CDS,3996,4276,.,+,2,ID=AT1G01010:CDS:2;Name=NAC001:CDS:2;Parent=AT...
4,Chr1,Araport11,CDS,4486,4605,.,+,0,ID=AT1G01010:CDS:3;Name=NAC001:CDS:3;Parent=AT...

In [ ]:
gff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 927529 entries, 0 to 927528
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Chromosome  927529 non-null  object
 1   Source      927529 non-null  object
 2   Feature     927529 non-null  object
 3   Start       927529 non-null  int64
 4   End         927529 non-null  int64
 5   Score       927529 non-null  object
 6   Strand      927529 non-null  object
 7   Frame       927529 non-null  object
 8   Attributes  927529 non-null  object
dtypes: int64(2), object(7)
memory usage: 63.7+ MB

In [ ]:
snps_ri.head()

       Chromosome    Start1
1374            1    505948
1445            1    523651
30676           1  10421043
30680           1  10421227
49286           1  13460657

In [ ]:
snps_ri.head()

       Chromosome    Start1
1374            1    505948
1445            1    523651
30676           1  10421043
30680           1  10421227
49286           1  13460657

In [ ]:
snps_ri["Chromosome"] = "Chr" + snps_ri["Chromosome"].astype(str)
#snps_gr["Chromosome"] = "Chr" + snps_gr["Chromosome"].astype(str)

In [ ]:
snps_ri.shape

(75, 2)

In [ ]:
snps_ri.info()

<class 'pandas.core.frame.DataFrame'>
Index: 518 entries, 1374 to 511863
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Chromosome  518 non-null    object
 1   Start1      518 non-null    int64
dtypes: int64(1), object(1)
memory usage: 12.1+ KB

In [ ]:
mask = (
    gff["Chromosome"].isin(snps_ri["Chromosome"]) &
    gff.apply(lambda row: any(
        (snps_ri["Chromosome"] == row["Chromosome"]) &
        (snps_ri["Start1"].between(row["Start"], row["End"]))
    ), axis=1)
)

filt_ri = gff[mask]

In [ ]:
# mask1 = (
#     gff["Chromosome"].isin(snps_gr["Chromosome"]) &
#     gff.apply(lambda row: any(
#         (snps_gr["Chromosome"] == row["Chromosome"]) &
#         (snps_gr["Start1"].between(row["Start"], row["End"]))
#     ), axis=1)
# )

# filt_gr = gff[mask1]

In [ ]:
filt_ri.shape

(237, 9)

In [ ]:
#save as csv
# filt_gr.to_csv('snp_grs.csv')

In [ ]:
# count the number of mutations per chromosme.
snp_chrom = filt_ri.groupby(['Chromosome','Feature'])['Attributes'].count().reset_index()
snp_chrom_pivot = snp_chrom.pivot(index = 'Feature', columns='Chromosome', values='Attributes')
snp_chrom_pivot

Chromosome                 Chr1  Chr2  Chr3  Chr4  Chr5
Feature
CDS                         4.0   3.0   1.0   NaN   4.0
exon                        7.0   9.0   5.0   2.0   7.0
five_prime_UTR              2.0   NaN   2.0   NaN   2.0
gene                        6.0   2.0   6.0   3.0   7.0
lnc_RNA                     NaN   NaN   1.0   NaN   NaN
mRNA                        9.0  11.0  10.0   5.0  34.0
protein                     4.0   5.0   2.0   3.0  25.0
pseudogene                  NaN   NaN   1.0   NaN   NaN
pseudogenic_exon            NaN   NaN   1.0   NaN   NaN
pseudogenic_transcript      NaN   NaN   1.0   NaN   NaN
three_prime_UTR             1.0   4.0   NaN   1.0   1.0
transcript_region           NaN   NaN   1.0   NaN   NaN
transposable_element        4.0   6.0   1.0   7.0   2.0
transposable_element_gene   2.0   2.0   NaN   1.0   NaN
transposon_fragment         4.0   6.0   1.0   7.0   2.0

In [ ]:
# extract the gene id from the Attribute.
filt_ri["Gene_ID"] = filt_ri["Attributes"].str.extract(r'ID=([^.:;]+)')

/tmp/ipykernel_8802/3590327075.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filt_ri["Gene_ID"] = filt_ri["Attributes"].str.extract(r'ID=([^.:;]+)')

In [ ]:
filt_ri.head()

,Chromosome,Source,Feature,Start,End,Score,Strand,Frame,Attributes,Gene_ID
5757,Chr1,Araport11,gene,504463,507268,.,-,.,ID=AT1G02460;Name=AT1G02460;Dbxref=TAIR:219605...,AT1G02460
5758,Chr1,Araport11,mRNA,504463,507268,.,-,.,ID=AT1G02460.1;Name=AT1G02460.1;Parent=AT1G024...,AT1G02460
5761,Chr1,Araport11,CDS,505845,506052,.,-,0,ID=AT1G02460:CDS:4;Name=AT1G02460:CDS:4;Parent...,AT1G02460
5767,Chr1,Araport11,exon,505845,506052,.,-,.,ID=AT1G02460:exon:4;Name=AT1G02460:exon:4;Pare...,AT1G02460
5772,Chr1,Araport11,protein,504897,507099,.,-,.,ID=AT1G02460.1-Protein;Name=AT1G02460.1;Derive...,AT1G02460

In [ ]:
# filter snps with in protein coding genes.
protein = filt_ri.query('Feature =="protein"')
protein

,Chromosome,Source,Feature,Start,End,Score,Strand,Frame,Attributes,Gene_ID
5772,Chr1,Araport11,protein,504897,507099,.,-,.,ID=AT1G02460.1-Protein;Name=AT1G02460.1;Derive...,AT1G02460
122912,Chr1,Araport11,protein,17021637,17022614,.,+,.,ID=AT1G45015.1-Protein;Name=AT1G45015.1;Derive...,AT1G45015
122924,Chr1,Araport11,protein,17021704,17022614,.,+,.,ID=AT1G45015.2-Protein;Name=AT1G45015.2;Derive...,AT1G45015
175529,Chr1,Araport11,protein,23727927,23729174,.,+,.,ID=AT1G63930.1-Protein;Name=AT1G63930.1;Derive...,AT1G63930
308002,Chr2,Araport11,protein,11528515,11530858,.,-,.,ID=AT2G27020.1-Protein;Name=AT2G27020.1;Derive...,AT2G27020
308026,Chr2,Araport11,protein,11528515,11531164,.,-,.,ID=AT2G27020.2-Protein;Name=AT2G27020.2;Derive...,AT2G27020
357603,Chr2,Araport11,protein,17345597,17346701,.,-,.,ID=AT2G41600.3-Protein;Name=AT2G41600.3;Derive...,AT2G41600
357625,Chr2,Araport11,protein,17344747,17346701,.,-,.,ID=AT2G41600.5-Protein;Name=AT2G41600.5;Derive...,AT2G41600
357643,Chr2,Araport11,protein,17345597,17346770,.,-,.,ID=AT2G41600.7-Protein;Name=AT2G41600.7;Derive...,AT2G41600
402510,Chr3,Araport11,protein,878388,880400,.,-,.,ID=AT3G03630.1-Protein;Name=AT3G03630.1;Derive...,AT3G03630
500654,Chr3,Araport11,protein,16328792,16330265,.,+,.,ID=AT3G44790.1-Protein;Name=AT3G44790.1;Derive...,AT3G44790
611247,Chr4,Araport11,protein,7787822,7791149,.,-,.,ID=AT4G13400.1-Protein;Name=AT4G13400.1;Derive...,AT4G13400
611277,Chr4,Araport11,protein,7788043,7791149,.,-,.,ID=AT4G13400.2-Protein;Name=AT4G13400.2;Derive...,AT4G13400
611404,Chr4,Araport11,protein,7804194,7807789,.,-,.,ID=AT4G13430.1-Protein;Name=AT4G13430.1;Derive...,AT4G13430
757244,Chr5,Araport11,protein,4035891,4041255,.,-,.,ID=AT5G12440.10-Protein;Name=AT5G12440.10;Deri...,AT5G12440
757340,Chr5,Araport11,protein,4035891,4041255,.,-,.,ID=AT5G12440.3-Protein;Name=AT5G12440.3;Derive...,AT5G12440
757388,Chr5,Araport11,protein,4035891,4041255,.,-,.,ID=AT5G12440.5-Protein;Name=AT5G12440.5;Derive...,AT5G12440
757414,Chr5,Araport11,protein,4035891,4041255,.,-,.,ID=AT5G12440.6-Protein;Name=AT5G12440.6;Derive...,AT5G12440
757466,Chr5,Araport11,protein,4035891,4041255,.,-,.,ID=AT5G12440.8-Protein;Name=AT5G12440.8;Derive...,AT5G12440
792061,Chr5,Araport11,protein,8028461,8030730,.,+,.,ID=AT5G23810.1-Protein;Name=AT5G23810.1;Derive...,AT5G23810
792077,Chr5,Araport11,protein,8028461,8030138,.,+,.,ID=AT5G23810.2-Protein;Name=AT5G23810.2;Derive...,AT5G23810
792090,Chr5,Araport11,protein,8028461,8029522,.,+,.,ID=AT5G23810.3-Protein;Name=AT5G23810.3;Derive...,AT5G23810
792106,Chr5,Araport11,protein,8028461,8029737,.,+,.,ID=AT5G23810.4-Protein;Name=AT5G23810.4;Derive...,AT5G23810
792121,Chr5,Araport11,protein,8028461,8029522,.,+,.,ID=AT5G23810.5-Protein;Name=AT5G23810.5;Derive...,AT5G23810
839525,Chr5,Araport11,protein,18260441,18264346,.,+,.,ID=AT5G45150.1-Protein;Name=AT5G45150.1;Derive...,AT5G45150
848958,Chr5,Araport11,protein,19489530,19492582,.,-,.,ID=AT5G48100.1-Protein;Name=AT5G48100.1;Derive...,AT5G48100
884889,Chr5,Araport11,protein,24031346,24035100,.,+,.,ID=AT5G59650.1-Protein;Name=AT5G59650.1;Derive...,AT5G59650
884918,Chr5,Araport11,protein,24031346,24035100,.,+,.,ID=AT5G59650.2-Protein;Name=AT5G59650.2;Derive...,AT5G59650
900960,Chr5,Araport11,protein,25788069,25790204,.,+,.,ID=AT5G64520.1-Protein;Name=AT5G64520.1;Derive...,AT5G64520
900982,Chr5,Araport11,protein,25788069,25790294,.,+,.,ID=AT5G64520.10-Protein;Name=AT5G64520.10;Deri...,AT5G64520
901002,Chr5,Araport11,protein,25788069,25790041,.,+,.,ID=AT5G64520.11-Protein;Name=AT5G64520.11;Deri...,AT5G64520
901024,Chr5,Araport11,protein,25788069,25790242,.,+,.,ID=AT5G64520.2-Protein;Name=AT5G64520.2;Derive...,AT5G64520
901046,Chr5,Araport11,protein,25788069,25790242,.,+,.,ID=AT5G64520.3-Protein;Name=AT5G64520.3;Derive...,AT5G64520
901066,Chr5,Araport11,protein,25788069,25790204,.,+,.,ID=AT5G64520.4-Protein;Name=AT5G64520.4;Derive...,AT5G64520
901088,Chr5,Araport11,protein,25788069,25790199,.,+,.,ID=AT5G64520.5-Protein;Name=AT5G64520.5;Derive...,AT5G64520
901110,Chr5,Araport11,protein,25788069,25790294,.,+,.,ID=AT5G64520.6-Protein;Name=AT5G64520.6;Derive...,AT5G64520
901126,Chr5,Araport11,protein,25788069,25789750,.,+,.,ID=AT5G64520.7-Protein;Name=AT5G64520.7;Derive...,AT5G64520
901138,Chr5,Araport11,protein,25788069,25789227,.,+,.,ID=AT5G64520.8-Protein;Name=AT5G64520.8;Derive...,AT5G64520
901160,Chr5,Araport11,protein,25788069,25790199,.,+,.,ID=AT5G64520.9-Protein;Name=AT5G64520.9;Derive...,AT5G64520

In [ ]:
protein.to_csv('snp_ri_proteins.csv')

In [ ]:
snp_df.to_csv('snp_ri_gene_id.csv')

In [ ]:
snp_prot = protein.drop(columns=['Attributes'])

In [ ]:
snp_prot = protein.drop_duplicates()

In [ ]:
snp_prot.shape

(39, 10)

In [ ]:
gr = pd.read_csv('/content/GR_pheno.hmp.txt', sep='\t')
gr1 = gr.drop(columns='RG')
gr1.head()

   <Trait>     GR
0      991  0.475
1     1062  0.689
2     1063  0.211
3     1254  0.635
4     1925  0.378

In [ ]:
# save as .hmp file.
gr1.to_csv('gr.hmp.txt', sep='\t', index=False)

In [ ]:
rg = gr.drop(columns='GR')
rg.head()

   <Trait>    RG
0      991  0.80
1     1062  1.22
2     1063  0.87
3     1254  1.39
4     1925  0.86

In [ ]:
rg.to_csv('rg.hmp.txt', sep='\t', index=False)

In [ ]:
from statsmodels.stats.multitest import multipletests

In [ ]:
gr_mlm = pd.read_csv('/content/growth_rate_mlm.csv.txt')
gr_mlm = gr_mlm[gr_mlm['p'].notna()]
gr_mlm = gr_mlm.drop(columns = ['add_effect','add_F','add_p','dom_effect',	'dom_F',	'dom_p'])
gr_mlm.head()

,Trait,Marker,Chr,Pos,df,F,p,errordf,MarkerR2,Genetic Var,Residual Var,-2LnLikelihood
1,GR,17963.0,1.0,6859595.0,1,11.80095,0.000722,202,0.05909,0.03329,0.01541,-206.82
2,GR,18498.0,1.0,7028768.0,1,12.37698,0.000540,202,0.06198,0.03329,0.01541,-206.82
3,GR,18502.0,1.0,7029418.0,1,11.21238,0.000973,202,0.05615,0.03329,0.01541,-206.82
4,GR,20872.0,1.0,7706945.0,1,13.56136,0.000298,202,0.06791,0.03329,0.01541,-206.82
5,GR,22258.0,1.0,8053830.0,1,12.94569,0.000406,202,0.06483,0.03329,0.01541,-206.82

In [ ]:
gr_mlm['p'] = pd.to_numeric(gr_mlm['p'], errors='coerce')

In [ ]:
gr_mlm['log10(p)'] = -np.log10(gr_mlm['p']).round(2)
gr_mlm.sort_values(by='log10(p)', ascending=False)

,Trait,Marker,Chr,Pos,df,F,p,errordf,MarkerR2,Genetic Var,Residual Var,-2LnLikelihood,fdr,log10(p)
282,GR,360462.0,4.0,7830236.0,1,24.65274,0.000001,202,0.12345,0.03329,0.01541,-206.82,0.000583,5.83
283,GR,360468.0,4.0,7830657.0,1,21.99018,0.000005,202,0.11012,0.03329,0.01541,-206.82,0.000777,5.29
205,GR,278569.0,3.0,15525441.0,1,21.67314,0.000006,202,0.10853,0.03329,0.01541,-206.82,0.000777,5.23
285,GR,360478.0,4.0,7831431.0,1,19.92938,0.000014,202,0.09980,0.03329,0.01541,-206.82,0.000994,4.87
210,GR,286904.0,3.0,16328933.0,1,19.40035,0.000017,202,0.09715,0.03329,0.01541,-206.82,0.000994,4.76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,GR,220364.0,3.0,4494180.0,1,11.21933,0.000970,202,0.05618,0.03329,0.01541,-206.82,0.000994,3.01
3,GR,18502.0,1.0,7029418.0,1,11.21238,0.000973,202,0.05615,0.03329,0.01541,-206.82,0.000994,3.01
269,GR,360226.0,4.0,7792537.0,1,11.18191,0.000989,202,0.05599,0.03329,0.01541,-206.82,0.000994,3.00
165,GR,216802.0,3.0,3275910.0,1,11.17001,0.000995,202,0.05593,0.03329,0.01541,-206.82,0.000995,3.00
168,GR,216877.0,3.0,3304530.0,1,11.17124,0.000994,202,0.05594,0.03329,0.01541,-206.82,0.000995,3.00

In [ ]:
gr_full = pd.read_csv('/content/growth_rate_full.csv.txt')

In [ ]:
gr_full = gr_full.drop(columns = ['add_effect','add_F','add_p','dom_effect',	'dom_F',	'dom_p'])
gr_full = gr_full[gr_full['p'].notna()]

In [ ]:
# based on the p value of gr_mlm, calculate the fdr values for each marker.
gr_full['fdr'] = multipletests(gr_full['p'], method='fdr_bh')[1]
gr_full.sort_values(by='fdr', ascending=True)

,Trait,Marker,Chr,Pos,df,F,p,errordf,MarkerR2,Genetic Var,Residual Var,-2LnLikelihood,fdr
360463,GR,360462.0,4.0,7830236.0,1,2.465274e+01,0.000001,202,1.234500e-01,0.03329,0.01541,-206.82,0.759627
148268,GR,148267.0,2.0,3684580.0,1,1.166220e+00,0.281500,202,5.840000e-03,0.03329,0.01541,-206.82,0.992587
348231,GR,348230.0,4.0,6016179.0,1,1.768710e+00,0.185080,202,8.860000e-03,0.03329,0.01541,-206.82,0.992587
277928,GR,277927.0,3.0,15407506.0,1,3.906850e+00,0.049490,202,1.956000e-02,0.03329,0.01541,-206.82,0.992587
277930,GR,277929.0,3.0,15407835.0,1,1.744170e+00,0.188140,202,8.730000e-03,0.03329,0.01541,-206.82,0.992587
...,...,...,...,...,...,...,...,...,...,...,...,...,...
449035,GR,449034.0,5.0,13284020.0,1,3.334800e-10,0.999990,202,1.669900e-12,0.03329,0.01541,-206.82,0.999998
10519,GR,10518.0,1.0,4163941.0,1,1.806500e-12,1.000000,202,9.046000e-15,0.03329,0.01541,-206.82,1.000000
360106,GR,360105.0,4.0,7781610.0,1,2.244500e-11,1.000000,202,1.123900e-13,0.03329,0.01541,-206.82,1.000000
218610,GR,218609.0,3.0,3747604.0,1,1.037000e-12,1.000000,202,5.192800e-15,0.03329,0.01541,-206.82,1.000000
483525,GR,483524.0,5.0,18802197.0,1,1.279100e-11,1.000000,202,6.405200e-14,0.03329,0.01541,-206.82,1.000000

In [ ]:
rg_full = pd.read_csv('/content/relative_growth_all.csv.txt')
rg_full = rg_full.drop(columns = ['add_effect','add_F','add_p','dom_effect',	'dom_F',	'dom_p'])
rg_full = rg_full[rg_full['p'].notna()]
rg_full['fdr'] = multipletests(rg_full['p'], method='fdr_bh')[1]
rg_full.sort_values(by='fdr', ascending=True)

,Trait,Marker,Chr,Pos,df,F,p,errordf,MarkerR2,Genetic Var,Residual Var,-2LnLikelihood,fdr
286903,RG,286902.0,3.0,16328861.0,1,2.727572e+01,4.466600e-07,202,1.370500e-01,0.06251,0.07539,105.21066,0.114379
286905,RG,286904.0,3.0,16328933.0,1,2.733193e+01,4.354100e-07,202,1.373300e-01,0.06251,0.07539,105.21066,0.114379
347687,RG,347686.0,4.0,5923054.0,1,2.432079e+01,1.728800e-06,202,1.222000e-01,0.06251,0.07539,105.21066,0.295137
266593,RG,266592.0,3.0,13530893.0,1,6.411500e-01,4.242600e-01,202,3.220000e-03,0.06251,0.07539,105.21066,0.999160
266611,RG,266610.0,3.0,13534231.0,1,2.436200e-01,6.221500e-01,202,1.220000e-03,0.06251,0.07539,105.21066,0.999160
...,...,...,...,...,...,...,...,...,...,...,...,...,...
328789,RG,328788.0,4.0,2411354.0,1,4.259300e-11,9.999900e-01,202,2.140200e-13,0.06251,0.07539,105.21066,0.999996
382482,RG,382481.0,4.0,11250069.0,1,6.260600e-11,9.999900e-01,202,3.145800e-13,0.06251,0.07539,105.21066,0.999996
50868,RG,50867.0,1.0,13752506.0,1,3.159100e-11,1.000000e+00,202,1.587400e-13,0.06251,0.07539,105.21066,1.000000
481970,RG,481969.0,5.0,18554140.0,1,1.894900e-11,1.000000e+00,202,9.521400e-14,0.06251,0.07539,105.21066,1.000000
275282,RG,275281.0,3.0,15051504.0,1,4.110800e-12,1.000000e+00,202,2.065500e-14,0.06251,0.07539,105.21066,1.000000

In [ ]:
gr_mlm = mlm_df.query('Trait == "GR"')
gr_mlm.head()

,Trait,Marker,Chr,Pos,df,F,p,add_effect,add_F,add_p,dom_effect,dom_F,dom_p,errordf,MarkerR2,Genetic Var,Residual Var,-2LnLikelihood,fdr
1024311,GR,0.0,1.0,92.0,1,0.119230,0.73024,NaN,NaN,NaN,NaN,NaN,NaN,202,0.000602,0.01532,1.531600e-07,-165.9,0.999806
1024312,GR,1.0,1.0,110.0,1,0.000836,0.97696,NaN,NaN,NaN,NaN,NaN,NaN,202,0.000004,0.01532,1.531600e-07,-165.9,0.999865
1024313,GR,2.0,1.0,253.0,1,0.010470,0.91860,NaN,NaN,NaN,NaN,NaN,NaN,202,0.000053,0.01532,1.531600e-07,-165.9,0.999806
1024314,GR,3.0,1.0,346.0,1,1.591830,0.20856,NaN,NaN,NaN,NaN,NaN,NaN,202,0.008030,0.01532,1.531600e-07,-165.9,0.999806
1024315,GR,4.0,1.0,353.0,1,2.304380,0.13061,NaN,NaN,NaN,NaN,NaN,NaN,202,0.011630,0.01532,1.531600e-07,-165.9,0.999806

In [ ]:
#rg_full = pd.read_csv('/content/relative_growth_all.csv.txt')
#rg_full = rg_full.drop(columns = ['add_effect','add_F','add_p','dom_effect',	'dom_F',	'dom_p'])
mlm_df = mlm_df[mlm_df['p'].notna()]
mlm_df['fdr'] = multipletests(mlm_df['p'], method='fdr_bh')[1]
mlm_df.sort_values(by='fdr', ascending=True)

,Trait,Marker,Chr,Pos,df,F,p,add_effect,add_F,add_p,dom_effect,dom_F,dom_p,errordf,MarkerR2,Genetic Var,Residual Var,-2LnLikelihood,fdr
1078378,GR,54067.0,1.0,14708014.0,1,3.968768e+01,1.906800e-09,NaN,NaN,NaN,NaN,NaN,NaN,202,2.002300e-01,0.01532,1.531600e-07,-165.90000,0.000419
1179632,GR,155321.0,2.0,4851488.0,1,3.968768e+01,1.906800e-09,NaN,NaN,NaN,NaN,NaN,NaN,202,2.002300e-01,0.01532,1.531600e-07,-165.90000,0.000419
1452529,GR,428218.0,5.0,8764474.0,1,3.968768e+01,1.906800e-09,NaN,NaN,NaN,NaN,NaN,NaN,202,2.002300e-01,0.01532,1.531600e-07,-165.90000,0.000419
1359880,GR,335569.0,4.0,3653126.0,1,3.968768e+01,1.906800e-09,NaN,NaN,NaN,NaN,NaN,NaN,202,2.002300e-01,0.01532,1.531600e-07,-165.90000,0.000419
1290596,GR,266285.0,3.0,13479155.0,1,3.968768e+01,1.906800e-09,NaN,NaN,NaN,NaN,NaN,NaN,202,2.002300e-01,0.01532,1.531600e-07,-165.90000,0.000419
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590949,IR,78793.0,1.0,19813803.0,1,1.313700e-12,1.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,202,6.471300e-15,0.03006,5.716000e-02,123.33577,1.000000
659300,IR,147144.0,2.0,3192135.0,1,2.573100e-11,1.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,202,1.267600e-13,0.03006,5.716000e-02,123.33577,1.000000
1081040,GR,56729.0,1.0,15756274.0,1,1.541300e-16,1.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,202,1.516700e-13,0.01532,1.531600e-07,-165.90000,1.000000
1132896,GR,108585.0,1.0,24743714.0,1,2.583400e-11,1.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,202,1.346000e-12,0.01532,1.531600e-07,-165.90000,1.000000
147145,RI,147144.0,2.0,3192135.0,1,2.516000e-11,1.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,202,1.239400e-13,0.03006,5.716000e-02,123.33577,1.000000

In [ ]:
gr_mlm = gr_mlm[gr_mlm['p'].notna()]
gr_mlm['fdr'] = multipletests(gr_mlm['p'], method='fdr_bh')[1]
gr_mlm.sort_values(by='fdr', ascending=True)

,Trait,Marker,Chr,Pos,df,F,p,add_effect,add_F,add_p,dom_effect,dom_F,dom_p,errordf,MarkerR2,Genetic Var,Residual Var,-2LnLikelihood,fdr
1359880,GR,335569.0,4.0,3653126.0,1,3.968768e+01,1.906800e-09,NaN,NaN,NaN,NaN,NaN,NaN,202,2.002300e-01,0.01532,1.531600e-07,-165.9,0.00014
1179632,GR,155321.0,2.0,4851488.0,1,3.968768e+01,1.906800e-09,NaN,NaN,NaN,NaN,NaN,NaN,202,2.002300e-01,0.01532,1.531600e-07,-165.9,0.00014
1213214,GR,188903.0,2.0,11952854.0,1,3.968768e+01,1.906800e-09,NaN,NaN,NaN,NaN,NaN,NaN,202,2.002300e-01,0.01532,1.531600e-07,-165.9,0.00014
1452529,GR,428218.0,5.0,8764474.0,1,3.968768e+01,1.906800e-09,NaN,NaN,NaN,NaN,NaN,NaN,202,2.002300e-01,0.01532,1.531600e-07,-165.9,0.00014
1078378,GR,54067.0,1.0,14708014.0,1,3.968768e+01,1.906800e-09,NaN,NaN,NaN,NaN,NaN,NaN,202,2.002300e-01,0.01532,1.531600e-07,-165.9,0.00014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1373010,GR,348699.0,4.0,6096089.0,1,1.731800e-11,1.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,202,1.180000e-13,0.01532,1.531600e-07,-165.9,1.00000
1081040,GR,56729.0,1.0,15756274.0,1,1.541300e-16,1.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,202,1.516700e-13,0.01532,1.531600e-07,-165.9,1.00000
1132896,GR,108585.0,1.0,24743714.0,1,2.583400e-11,1.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,202,1.346000e-12,0.01532,1.531600e-07,-165.9,1.00000
1470394,GR,446083.0,5.0,12528373.0,1,8.287300e-12,1.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,202,4.181000e-14,0.01532,1.531600e-07,-165.9,1.00000
1527073,GR,502762.0,5.0,23932251.0,1,2.774000e-11,1.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,202,1.989800e-13,0.01532,1.531600e-07,-165.9,1.00000